### ISSUE TITLE
dropped connectivity while restarting calico/node (master build)

### ISSUE THREAD

**Issue by frnkdny** [projectcalico/felix#1592] opened 2017-10-27 03:40 UTC
## Expected Behavior

kubectl delete of calico-node should not result in dropped connectivity.

## Current Behavior

3 node kubeadm cluster running:
`getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml`

Observed more than 100 seconds of dropped connectivity 

## Steps to Reproduce (for bugs)

```
There are 2 worker nodes.
fd-crc-kubeadm-node-0
fd-crc-kubeadm-node-1

kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP             NODE
iperf-7d5bd8f779-cqfdh   1/1       Running   0          26m       192.168.2.24   fd-crc-kubeadm-node-1
iperf-7d5bd8f779-ljvj5   1/1       Running   0          26m       192.168.1.23   fd-crc-kubeadm-node-0

iperf client: iperf-7d5bd8f779-ljvj5
iperf server ip: 192.168.2.24

kubectl exec iperf-7d5bd8f779-ljvj5 -- sh -c "iperf -c 192.168.2.24 -t 3600 -i 1" 

calico-node output on fd-crc-kubeadm-node-0: calico-node-pndrk   2/2       Running   0          2m        10.128.0.6   fd-crc-kubeadm-node-0
deleting: calico-node-pndrk

pod "calico-node-pndrk" deleted

calico-node output on fd-crc-kubeadm-node-0: calico-node-7hsqn   2/2       Running   0          5s        10.128.0.6   fd-crc-kubeadm-node-0
deleting: calico-node-7hsqn

pod "calico-node-7hsqn" deleted

iperf/iperf-logs
------------------------------------------------------------
Client connecting to 192.168.2.24, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 192.168.1.23 port 42628 connected with 192.168.2.24 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 1.0 sec   571 MBytes  4.79 Gbits/sec
[  3]  1.0- 2.0 sec   549 MBytes  4.60 Gbits/sec
[  3]  2.0- 3.0 sec   636 MBytes  5.33 Gbits/sec
[  3]  3.0- 4.0 sec   534 MBytes  4.48 Gbits/sec
[  3]  4.0- 5.0 sec   553 MBytes  4.64 Gbits/sec
<snip>
[  3] 95.0-96.0 sec   634 MBytes  5.32 Gbits/sec
[  3] 96.0-97.0 sec   578 MBytes  4.85 Gbits/sec
[  3] 97.0-98.0 sec   583 MBytes  4.89 Gbits/sec
[  3] 98.0-99.0 sec   122 MBytes  1.02 Gbits/sec
[  3] 99.0-100.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 100.0-101.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 101.0-102.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 102.0-103.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 103.0-104.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 104.0-105.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 105.0-106.0 sec  0.00 Bytes  0.00 bits/sec
<snip>
[  3] 200.0-201.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 201.0-202.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 202.0-203.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 203.0-204.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 204.0-205.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 205.0-206.0 sec   200 MBytes  1.68 Gbits/sec
[  3] 206.0-207.0 sec   805 MBytes  6.75 Gbits/sec


kubectl get pods -n kube-system -o wide | grep calico-node
NAME                                            READY     STATUS    RESTARTS   AGE       IP            NODE
calico-node-5f44d                               2/2       Running   0          36m       10.128.0.2    fd-crc-kubeadm-master
calico-node-6bpsg                               2/2       Running   0          35m       10.128.0.5    fd-crc-kubeadm-node-1
calico-node-m9wtc                               2/2       Running   0          30m       10.128.0.6    fd-crc-kubeadm-node-0
```
## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
```
/ # /sbin/versions
confd v1.0.0-alpha1-rc3
BIRD version 1.6.3
libnetwork-plugin: v1.1.0-28-g20f511e
calico-bgp-daemon: v0.2.2

Felix:
2017-10-27 03:37:51.938 [INFO][656] logutils.go 83: Early screen log level set to debug
2017-10-27 03:37:51.938 [DEBUG][656] felix.go 125: No GOGC value set, defaulting to 20%.
Version:            3.0.0-alpha1-rc1-14-g5075dce9
Full git commit ID: 5075dce9678e46031c22fe7f0278bee7c5d0d9c5
Build date:         2017-10-26T15:25:59+0000
```
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by fasaxc** [comment] 2017-10-27 14:46
I've correlated the connectivity drop with the following `ip monitor` event:
```
Deleted 192.168.2.0/24 via 10.128.0.19 dev tunl0  proto bird onlink
```
on node-1; the calico/node that was terminated was on node-0.

After a while I see the route being restored:

```
192.168.2.0/24 via 10.128.0.19 dev tunl0  proto bird onlink 
```

Then, after another 10-20s, iperf starts to see traffic again (strange that there's a delay there, I don't understand that yet).

**Comment by fasaxc** [comment] 2017-10-27 16:59
Manually removing and restoring that route seems to give the same symptoms so I'm pretty sure that's the cause.  So why is bird withdrawing the route?

I tried adding a 30s sleep to the test before killing calico/node in order to give BGP time to stabilise.  That seems to reduce the frequency of the failure significantly.  I only saw one failure in three complete runs.

**Comment by fasaxc** [comment] 2017-10-27 17:18
With bird debug logs enabled, I managed to catch this after restarting the peer twice:
```
bird: Mesh_10_128_0_19: Connection closed
bird: Mesh_10_128_0_19: Neighbor graceful restart detected - already pending
bird: Mesh_10_128_0_19: State changed to start
bird: Mesh_10_128_0_19: BGP session closed
bird: Mesh_10_128_0_19 > removed [sole] 192.168.2.0/24 via 10.128.0.1 on ens4
bird: kernel1 < removed 192.168.2.0/24 via 10.128.0.1 on ens4
```
Looks like the first GR hadn't been marked as done yet so it cancelled GR and reverted to a normal start.

**Comment by fasaxc** [comment] 2017-10-27 17:46
Also managed to hit the same log with @frnkdny's original repro script so I think this is our issue.

**Comment by fasaxc** [comment] 2017-10-30 10:17
I _think_ BIRD is working as designed here.  This is what RFC 4724 has to say about consecutive restarts:
```
   When the Receiving Speaker detects termination of the TCP session for
   a BGP session with a peer that has advertised the Graceful Restart
   Capability, it MUST retain the routes received from the peer for all
   the address families that were previously received in the Graceful
   Restart Capability and MUST mark them as stale routing information.
   To deal with possible consecutive restarts, a route (from the peer)
   previously marked as stale MUST be deleted.  The router MUST NOT
   differentiate between stale and other routing information during
   forwarding.
```
Unfortunately, the resulting behaviour is sub-optimal for Calico (at least in this particular scenario).

**Comment by fasaxc** [comment] 2017-10-30 10:20
Still to investigate:
- [ ] Why does this result in such a long period of dropped traffic.
- [ ] Why does v3.0.0 seem to be worse than v2.6.x here

**Comment by fasaxc** [comment] 2017-10-30 11:02
One contributor to the long timeout is that the routes are discarded from the dataplane as soon as the second restart begins.  Then it seems to take a long time for calico/node to terminate and be rescheduled (as seen on the kubectl output).  Unclear if that slowness is due to k8s async or if the container really does take a long time to stop.

**Comment by fasaxc** [comment] 2017-11-01 10:22
@frnkdny did some comparative testing and found that k8s 1.8 changed the termination behaviour for a pod in this scenario.  Previously, the new calico/node pod would be started while the old one was in the terminating state.  In k8s 1.8 that seems to have changed so the terminating state is blocking.

**Comment by fasaxc** [comment] 2017-11-01 11:12
Looks like k8s 1.8 includes a fix to make the daemonset controller honour the termination grace period: https://github.com/kubernetes/kubernetes/pull/51279 

It appears that our install_cni.sh container doesn't honour sigterm so it blocks the shutdown of the pod until the default grace period expires.

**Closed** 2017-11-02 15:53 UTC
Labels: kind/bug, priority/P1
