### ISSUE TITLE
vm can't dhcp ip

### ISSUE THREAD

**Issue by guanyuding** [projectcalico/felix#993] opened 2016-03-15 10:59 UTC
we can see the result on network node
# nova list
+--------------------------------------+------+--------+------------+-------------+------------------------+
| ID                                   | Name | Status | Task State | Power State | Networks               |
+--------------------------------------+------+--------+------------+-------------+------------------------+
| 4aae36e3-dab5-43ca-b019-0f1afeb0e39c | www  | ACTIVE | -          | Running     | internal=192.168.1.107 |
| 63564a9d-01d6-4dd3-9c92-404386ff9e99 | www2 | ACTIVE | -          | Running     | internal=192.168.1.108 |
+--------------------------------------+------+--------+------------+-------------+------------------------+

but the vm  can't dhcp ip address,so run the command on compute node:
# tcpdump -i tap82d69e1a-1f
18:53:01.563359 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from fa:16:3e:1d:54:d4 (oui Unknown), length 300
18:53:05.051428 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from fa:16:3e:1d:54:d4 (oui Unknown), length 300

]# iptables-save 
# Generated by iptables-save v1.4.21 on Tue Mar 15 18:57:40 2016
*mangle
:PREROUTING ACCEPT [519632:4237374545]
:INPUT ACCEPT [519248:4237341350]
:FORWARD ACCEPT [373:31332]
:OUTPUT ACCEPT [489550:62044269]
:POSTROUTING ACCEPT [489313:61861705]
:neutron-dhcp-age-FORWARD - [0:0]
:neutron-dhcp-age-INPUT - [0:0]
:neutron-dhcp-age-OUTPUT - [0:0]
:neutron-dhcp-age-POSTROUTING - [0:0]
:neutron-dhcp-age-PREROUTING - [0:0]
:neutron-dhcp-age-mark - [0:0]
:neutron-linuxbri-FORWARD - [0:0]
:neutron-linuxbri-INPUT - [0:0]
:neutron-linuxbri-OUTPUT - [0:0]
:neutron-linuxbri-POSTROUTING - [0:0]
:neutron-linuxbri-PREROUTING - [0:0]
:neutron-linuxbri-mark - [0:0]
:neutron-openvswi-FORWARD - [0:0]
:neutron-openvswi-INPUT - [0:0]
:neutron-openvswi-OUTPUT - [0:0]
:neutron-openvswi-POSTROUTING - [0:0]
:neutron-openvswi-PREROUTING - [0:0]
:neutron-openvswi-mark - [0:0]
:nova-api-POSTROUTING - [0:0]
:nova-api-metadat-POSTROUTING - [0:0]
:nova-compute-POSTROUTING - [0:0]
-A PREROUTING -j neutron-dhcp-age-PREROUTING
-A PREROUTING -j neutron-linuxbri-PREROUTING
-A PREROUTING -j neutron-openvswi-PREROUTING
-A INPUT -j neutron-dhcp-age-INPUT
-A INPUT -j neutron-linuxbri-INPUT
-A INPUT -j neutron-openvswi-INPUT
-A FORWARD -j neutron-dhcp-age-FORWARD
-A FORWARD -j neutron-linuxbri-FORWARD
-A FORWARD -j neutron-openvswi-FORWARD
-A OUTPUT -j neutron-dhcp-age-OUTPUT
-A OUTPUT -j neutron-linuxbri-OUTPUT
-A OUTPUT -j neutron-openvswi-OUTPUT
-A OUTPUT -o tap+ -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A POSTROUTING -j nova-compute-POSTROUTING
-A POSTROUTING -j neutron-dhcp-age-POSTROUTING
-A POSTROUTING -j neutron-linuxbri-POSTROUTING
-A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A POSTROUTING -j nova-api-metadat-POSTROUTING
-A POSTROUTING -j neutron-openvswi-POSTROUTING
-A POSTROUTING -j nova-api-POSTROUTING
-A POSTROUTING -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A neutron-dhcp-age-POSTROUTING -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
-A neutron-dhcp-age-PREROUTING -j neutron-dhcp-age-mark
-A neutron-linuxbri-PREROUTING -j neutron-linuxbri-mark
-A neutron-openvswi-PREROUTING -j neutron-openvswi-mark
COMMIT
# Completed on Tue Mar 15 18:57:40 2016
# Generated by iptables-save v1.4.21 on Tue Mar 15 18:57:40 2016
*nat
:PREROUTING ACCEPT [1:84]
:INPUT ACCEPT [1:84]
:OUTPUT ACCEPT [16:2230]
:POSTROUTING ACCEPT [12:806]
:felix-PREROUTING - [0:0]
:neutron-dhcp-age-OUTPUT - [0:0]
:neutron-dhcp-age-POSTROUTING - [0:0]
:neutron-dhcp-age-PREROUTING - [0:0]
:neutron-dhcp-age-float-snat - [0:0]
:neutron-dhcp-age-snat - [0:0]
:neutron-linuxbri-OUTPUT - [0:0]
:neutron-linuxbri-POSTROUTING - [0:0]
:neutron-linuxbri-PREROUTING - [0:0]
:neutron-linuxbri-float-snat - [0:0]
:neutron-linuxbri-snat - [0:0]
:neutron-openvswi-OUTPUT - [0:0]
:neutron-openvswi-POSTROUTING - [0:0]
:neutron-openvswi-PREROUTING - [0:0]
:neutron-openvswi-float-snat - [0:0]
:neutron-openvswi-snat - [0:0]
:neutron-postrouting-bottom - [0:0]
:nova-api-OUTPUT - [0:0]
:nova-api-POSTROUTING - [0:0]
:nova-api-PREROUTING - [0:0]
:nova-api-float-snat - [0:0]
:nova-api-metadat-OUTPUT - [0:0]
:nova-api-metadat-POSTROUTING - [0:0]
:nova-api-metadat-PREROUTING - [0:0]
:nova-api-metadat-float-snat - [0:0]
:nova-api-metadat-snat - [0:0]
:nova-api-snat - [0:0]
:nova-compute-OUTPUT - [0:0]
:nova-compute-POSTROUTING - [0:0]
:nova-compute-PREROUTING - [0:0]
:nova-compute-float-snat - [0:0]
:nova-compute-snat - [0:0]
:nova-postrouting-bottom - [0:0]
-A PREROUTING -j felix-PREROUTING
-A PREROUTING -j nova-compute-PREROUTING
-A PREROUTING -j neutron-dhcp-age-PREROUTING
-A PREROUTING -j neutron-linuxbri-PREROUTING
-A PREROUTING -j nova-api-metadat-PREROUTING
-A PREROUTING -j neutron-openvswi-PREROUTING
-A PREROUTING -j nova-api-PREROUTING
-A OUTPUT -j nova-compute-OUTPUT
-A OUTPUT -j neutron-dhcp-age-OUTPUT
-A OUTPUT -j neutron-linuxbri-OUTPUT
-A OUTPUT -j nova-api-metadat-OUTPUT
-A OUTPUT -j neutron-openvswi-OUTPUT
-A OUTPUT -j nova-api-OUTPUT
-A POSTROUTING -j nova-compute-POSTROUTING
-A POSTROUTING -j neutron-dhcp-age-POSTROUTING
-A POSTROUTING -j neutron-postrouting-bottom
-A POSTROUTING -j neutron-linuxbri-POSTROUTING
-A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
-A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
-A POSTROUTING -j nova-api-metadat-POSTROUTING
-A POSTROUTING -j neutron-openvswi-POSTROUTING
-A POSTROUTING -j nova-api-POSTROUTING
-A POSTROUTING -j nova-postrouting-bottom
-A felix-PREROUTING -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 127.0.0.1:8775
-A neutron-dhcp-age-snat -j neutron-dhcp-age-float-snat
-A neutron-linuxbri-snat -j neutron-linuxbri-float-snat
-A neutron-openvswi-snat -j neutron-openvswi-float-snat
-A neutron-postrouting-bottom -m comment --comment "Perform source NAT on outgoing traffic." -j neutron-dhcp-age-snat
-A neutron-postrouting-bottom -m comment --comment "Perform source NAT on outgoing traffic." -j neutron-linuxbri-snat
-A neutron-postrouting-bottom -m comment --comment "Perform source NAT on outgoing traffic." -j neutron-openvswi-snat
-A nova-api-metadat-snat -j nova-api-metadat-float-snat
-A nova-api-snat -j nova-api-float-snat
-A nova-compute-snat -j nova-compute-float-snat
-A nova-postrouting-bottom -j nova-compute-snat
-A nova-postrouting-bottom -j nova-api-metadat-snat
-A nova-postrouting-bottom -j nova-api-snat
COMMIT
# Completed on Tue Mar 15 18:57:40 2016
# Generated by iptables-save v1.4.21 on Tue Mar 15 18:57:40 2016
*raw
:PREROUTING ACCEPT [102976346:38801634507]
:OUTPUT ACCEPT [110127615:19767267003]
:neutron-dhcp-age-OUTPUT - [0:0]
:neutron-dhcp-age-PREROUTING - [0:0]
:neutron-linuxbri-OUTPUT - [0:0]
:neutron-linuxbri-PREROUTING - [0:0]
:neutron-openvswi-OUTPUT - [0:0]
:neutron-openvswi-PREROUTING - [0:0]
-A PREROUTING -j neutron-dhcp-age-PREROUTING
-A PREROUTING -j neutron-linuxbri-PREROUTING
-A PREROUTING -j neutron-openvswi-PREROUTING
-A OUTPUT -j neutron-dhcp-age-OUTPUT
-A OUTPUT -j neutron-linuxbri-OUTPUT
-A OUTPUT -j neutron-openvswi-OUTPUT
COMMIT
# Completed on Tue Mar 15 18:57:40 2016
# Generated by iptables-save v1.4.21 on Tue Mar 15 18:57:40 2016
*filter
:INPUT ACCEPT [741:103500]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1062:153654]
:felix-FORWARD - [0:0]
:felix-FROM-ENDPOINT - [0:0]
:felix-INPUT - [0:0]
:felix-TO-ENDPOINT - [0:0]
:felix-from-82d69e1a-1f - [0:0]
:felix-p-_95e9c32c77a6dbf-i - [0:0]
:felix-p-_95e9c32c77a6dbf-o - [0:0]
:felix-to-82d69e1a-1f - [0:0]
:neutron-dhcp-age-FORWARD - [0:0]
:neutron-dhcp-age-INPUT - [0:0]
:neutron-dhcp-age-OUTPUT - [0:0]
:neutron-dhcp-age-local - [0:0]
:neutron-filter-top - [0:0]
:neutron-linuxbri-FORWARD - [0:0]
:neutron-linuxbri-INPUT - [0:0]
:neutron-linuxbri-OUTPUT - [0:0]
:neutron-linuxbri-local - [0:0]
:neutron-linuxbri-sg-chain - [0:0]
:neutron-linuxbri-sg-fallback - [0:0]
:neutron-openvswi-FORWARD - [0:0]
:neutron-openvswi-INPUT - [0:0]
:neutron-openvswi-OUTPUT - [0:0]
:neutron-openvswi-local - [0:0]
:neutron-openvswi-sg-chain - [0:0]
:neutron-openvswi-sg-fallback - [0:0]
:nova-api-FORWARD - [0:0]
:nova-api-INPUT - [0:0]
:nova-api-OUTPUT - [0:0]
:nova-api-local - [0:0]
:nova-api-metadat-FORWARD - [0:0]
:nova-api-metadat-INPUT - [0:0]
:nova-api-metadat-OUTPUT - [0:0]
:nova-api-metadat-local - [0:0]
:nova-compute-FORWARD - [0:0]
:nova-compute-INPUT - [0:0]
:nova-compute-OUTPUT - [0:0]
:nova-compute-inst-42 - [0:0]
:nova-compute-local - [0:0]
:nova-compute-provider - [0:0]
:nova-compute-sg-fallback - [0:0]
:nova-filter-top - [0:0]
-A INPUT -j felix-INPUT
-A INPUT -j nova-compute-INPUT
-A INPUT -j neutron-dhcp-age-INPUT
-A FORWARD -j felix-FORWARD
-A FORWARD -j nova-filter-top
-A FORWARD -j nova-compute-FORWARD
-A FORWARD -j neutron-filter-top
-A FORWARD -j neutron-dhcp-age-FORWARD
-A OUTPUT -j nova-filter-top
-A OUTPUT -j nova-compute-OUTPUT
-A OUTPUT -j neutron-filter-top
-A OUTPUT -j neutron-dhcp-age-OUTPUT
-A felix-FORWARD -i tap+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -o tap+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -i tap+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -o tap+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -i tap+ -j felix-FROM-ENDPOINT
-A felix-FORWARD -o tap+ -j felix-TO-ENDPOINT
-A felix-FORWARD -i tap+ -j ACCEPT
-A felix-FORWARD -o tap+ -j ACCEPT
-A felix-FROM-ENDPOINT -i tap82d69e1a-1f -g felix-from-82d69e1a-1f
-A felix-FROM-ENDPOINT -m comment --comment "From unknown endpoint" -j DROP
-A felix-INPUT ! -i tap+ -j RETURN
-A felix-INPUT -m conntrack --ctstate INVALID -j DROP
-A felix-INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A felix-INPUT -d 127.0.0.1/32 -p tcp -m tcp --dport 8775 -j ACCEPT
-A felix-INPUT -p udp -m udp --sport 68 --dport 67 -j ACCEPT
-A felix-INPUT -p udp -m udp --dport 53 -j ACCEPT
-A felix-INPUT -m comment --comment "Drop all packets from endpoints to the host" -j DROP
-A felix-TO-ENDPOINT -o tap82d69e1a-1f -g felix-to-82d69e1a-1f
-A felix-TO-ENDPOINT -m comment --comment "To unknown endpoint" -j DROP
-A felix-from-82d69e1a-1f -j MARK --set-xmark 0x0/0xffffffff
-A felix-from-82d69e1a-1f -m mac ! --mac-source FA:16:3E:1D:54:D4 -m comment --comment "Incorrect source MAC" -j DROP
-A felix-from-82d69e1a-1f -j felix-p-_95e9c32c77a6dbf-o
-A felix-from-82d69e1a-1f -m mark --mark 0x1/0x1 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-from-82d69e1a-1f -m comment --comment "Packet did not match any profile (endpoint 82d69e1a-1f1b-4fc7-a6b4-7e580b743c2b)" -j DROP
-A felix-p-_95e9c32c77a6dbf-i -j MARK --set-xmark 0x1/0xffffffff
-A felix-p-_95e9c32c77a6dbf-i -p udp -m multiport --dports 1:65535 -j RETURN
-A felix-p-_95e9c32c77a6dbf-i -p icmp -j RETURN
-A felix-p-_95e9c32c77a6dbf-i -p tcp -m multiport --dports 1:65535 -j RETURN
-A felix-p-_95e9c32c77a6dbf-i -m comment --comment "No match, fall through to next profile" -j MARK --set-xmark 0x0/0xffffffff
-A felix-p-_95e9c32c77a6dbf-o -j MARK --set-xmark 0x1/0xffffffff
-A felix-p-_95e9c32c77a6dbf-o -p udp -m multiport --dports 1:65535 -j RETURN
-A felix-p-_95e9c32c77a6dbf-o -p tcp -m multiport --dports 1:65535 -j RETURN
-A felix-p-_95e9c32c77a6dbf-o -p icmp -j RETURN
-A felix-p-_95e9c32c77a6dbf-o -m comment --comment "No match, fall through to next profile" -j MARK --set-xmark 0x0/0xffffffff
-A felix-to-82d69e1a-1f -j MARK --set-xmark 0x0/0xffffffff
-A felix-to-82d69e1a-1f -j felix-p-_95e9c32c77a6dbf-i
-A felix-to-82d69e1a-1f -m mark --mark 0x1/0x1 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-to-82d69e1a-1f -m comment --comment "Packet did not match any profile (endpoint 82d69e1a-1f1b-4fc7-a6b4-7e580b743c2b)" -j DROP
-A neutron-filter-top -j neutron-dhcp-age-local
-A nova-compute-inst-42 -m state --state INVALID -j DROP
-A nova-compute-inst-42 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A nova-compute-inst-42 -j nova-compute-provider
-A nova-compute-inst-42 -s 192.168.1.0/24 -j ACCEPT
-A nova-compute-inst-42 -j nova-compute-sg-fallback
-A nova-compute-local -d 192.168.1.107/32 -j nova-compute-inst-42
-A nova-compute-sg-fallback -j DROP
-A nova-filter-top -j nova-compute-local

**Comment by neiljerram** [comment] 2016-03-15 13:14
Hi @guanyuding, thanks for reporting this.  Here are a few questions:

- Do you have a DHCP agent and Dnsmasq running on the compute node?  Please show me the output of `ps waux | grep dhcp-agent` and `ps waux | grep dnsmasq`.

- Please can you look in /var/log/syslog or /var/log/messages for any dnsmasq logs that indicate failure to respond to the DHCP request from the VM.

- Could you do `ip r` and `ip l` on the compute node, so I can see routing and interfaces?

Thanks!

**Comment by guanyuding** [comment] 2016-03-16 04:07
@neiljerram   Thanks for your reply!
I looked in  /var/log/messages on my compute node,I think that has been assigned IP to my vm; 
# tail -f messages
Mar 16 11:59:11 c3-pt-compute24 dnsmasq-dhcp[7472]: DHCPDISCOVER(ns-5f44d9e6-7f) fa:16:3e:74:85:ab
Mar 16 11:59:11 c3-pt-compute24 dnsmasq-dhcp[7472]: DHCPOFFER(ns-5f44d9e6-7f) 192.168.1.108 fa:16:3e:74:85:ab
Mar 16 11:59:14 c3-pt-compute24 dnsmasq-dhcp[7472]: DHCPDISCOVER(ns-5f44d9e6-7f) fa:16:3e:74:85:ab
Mar 16 11:59:14 c3-pt-compute24 dnsmasq-dhcp[7472]: DHCPOFFER(ns-5f44d9e6-7f) 192.168.1.108 fa:16:3e:74:85:ab

But the response packets are dropped by iptables, Every time i created, It will generate such rules:
Chain nova-compute-inst-43 (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
       0        0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            state INVALID
       0        0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
    2563   912428 nova-compute-provider  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
       0        0 ACCEPT     all  --  *      *       192.168.1.0/24       0.0.0.0/0           
    2563   912428 nova-compute-sg-fallback  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain nova-compute-local (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
    2563   912428 nova-compute-inst-43  all  --  *      *       0.0.0.0/0            192.168.1.108       

Chain nova-compute-provider (1 references)
    pkts      bytes target     prot opt in     out     source               destination         

Chain nova-compute-sg-fallback (1 references)
    pkts      bytes target     prot opt in     out     source               destination         
    2563   912428 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0  

# ps waux | grep dhcp-agent
neutron  25582  2.0  0.0 317360 49888 ?        Ss   Mar15  27:00 /usr/bin/python2 /usr/bin/neutron-dhcp-agent --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/dhcp_agent.ini --config-dir /etc/neutron/conf.d/common --config-dir /etc/neutron/conf.d/neutron-dhcp-agent --log-file /var/log/neutron/dhcp-agent.log

# ps waux | grep dnsmasq
nobody    4705  0.0  0.0  15548   876 ?        S    Jan12   0:04 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root      4706  0.0  0.0  15520   180 ?        S    Jan12   0:00 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
nobody    7472  0.0  0.0   6692   848 ?        S    Mar15   0:01 /sbin/dnsmasq --no-hosts --no-resolv --strict-order --except-interface=lo --pid-file=/var/lib/neutron/dhcp/2a26e83e-1577-49c3-a4df-16b9453406c1/pid --dhcp-hostsfile=/var/lib/neutron/dhcp/2a26e83e-1577-49c3-a4df-16b9453406c1/host --addn-hosts=/var/lib/neutron/dhcp/2a26e83e-1577-49c3-a4df-16b9453406c1/addn_hosts --dhcp-optsfile=/var/lib/neutron/dhcp/2a26e83e-1577-49c3-a4df-16b9453406c1/opts --dhcp-leasefile=/var/lib/neutron/dhcp/2a26e83e-1577-49c3-a4df-16b9453406c1/leases --dhcp-match=set:ipxe,175 --bind-dynamic --interface=ns-5f44d9e6-7f --interface=tap* --bridge-interface=ns-5f44d9e6-7f,tap* --dhcp-range=set:tag0,192.168.1.0,static,86400s --dhcp-lease-max=256 --conf-file= --domain=openstacklocal --enable-ra
nobody    9557  0.0  0.0   6688   716 ?        S    Jan20   0:03 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
root      9558  0.0  0.0   6688   136 ?        S    Jan20   0:00 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

# ip r
default via 10.108.94.254 dev eth0 
10.108.94.0/24 dev eth0  proto kernel  scope link  src 10.108.94.19 
169.254.0.0/16 dev eth0  scope link  metric 1002 
192.168.1.107 via 10.108.94.17 dev eth0  proto bird 
192.168.1.108 dev tap6492354a-e2  scope link 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 

]# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT qlen 1000
    link/ether ec:f4:bb:ce:a6:ac brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
    link/ether ec:f4:bb:ce:a6:ad brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
    link/ether ec:f4:bb:ce:a6:a8 brd ff:ff:ff:ff:ff:ff
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master ovs-system state UP mode DEFAULT qlen 1000
    link/ether ec:f4:bb:ce:a6:aa brd ff:ff:ff:ff:ff:ff
6: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT 
    link/ether 62:3b:78:31:f3:31 brd ff:ff:ff:ff:ff:ff
7: br-eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/ether ec:f4:bb:ce:a6:aa brd ff:ff:ff:ff:ff:ff
8: br-int: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/ether aa:ae:1c:47:4a:4d brd ff:ff:ff:ff:ff:ff
9: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT 
    link/ether 52:54:00:e1:be:85 brd ff:ff:ff:ff:ff:ff
10: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN mode DEFAULT qlen 500
    link/ether 52:54:00:e1:be:85 brd ff:ff:ff:ff:ff:ff
43: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT 
    link/ether 3a:92:91:08:cb:33 brd ff:ff:ff:ff:ff:ff
77: ns-5f44d9e6-7f: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT 
    link/ether fa:16:3e:e3:65:8a brd ff:ff:ff:ff:ff:ff
81: tap6492354a-e2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 500
    link/ether 00:61:fe:ed:ca:fe brd ff:ff:ff:ff:ff:ff

**Comment by neiljerram** [comment] 2016-03-16 17:06
Thanks @guanyuding - I have an idea what the problem is now.

Can I ask what procedure you followed to install Calico?  It looks like you have multiple firewall implementations that are fighting with each other to install different sets of iptables rules - when it should just be Calico installing iptables rules.

Specifically I see that your iptables includes 'nova-*' chains.  Those should not be there, and to get rid of them I think you need

    security_group_api = neutron
    firewall_driver = nova.virt.firewall.NoopFirewallDriver

in your /etc/nova/nova.conf.  Could you check that?

Also you should not have any firewall settings in your /etc/neutron/neutron.conf.  Could you check that too?

Finally, you _should_ have rules to do checksumming for DHCP response in the 'mangle' table, like this:

    ubuntu@calico-vm09:~$ sudo iptables -t mangle -L
    ...
    CHECKSUM   udp  --  anywhere             anywhere             udp dpt:bootpc CHECKSUM fill
    ...
    ubuntu@calico-vm09:~$ 

Please check that also.

**Comment by guanyuding** [comment] 2016-03-17 06:11
thanks @neiljerram  I have tried your advice.but there is no effect about it;so this is nova.conf and neutron.conf of my  compute node, Could you check it for me？ then show your config of nova and neutron;thanks~

#c3-pt-compute23 is my control node;

# vim neutron.conf
[DEFAULT]
rpc_backend = rabbit
auth_strategy = keystone
notify_nova_on_port_status_changes = True
notify_nova_on_port_data_changes = True
core_plugin = ml2
service_plugins = router
allow_overlapping_ips = True
verbose = True
dhcp_agents_per_network = 9999

[oslo_messaging_rabbit]
rabbit_host = c3-pt-compute23.bj
rabbit_password = mistack
rabbit_userid = openstack

[keystone_authtoken]
auth_uri = http://c3-pt-compute23:5000
auth_url = http://c3-pt-compute23:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = neutron
password = mistack

[service_providers]
service_provider=VPN:openswan:neutron.services.vpn.service_drivers.ipsec.IPsecVPNDriver:default


# vim nova.conf
[DEFAULT]
rpc_backend = rabbit
auth_strategy = keystone
my_ip = 10.108.94.17
verbose = True
network_api_class = nova.network.neutronv2.api.API
enabled_apis = osapi_compute,metadata
log_dir=/var/log/nova
rabbit_max_retries = 0
vnc_enabled = True
resume_guests_state_on_host_boot = True
vif_plugging_timeout=300
vif_plugging_is_fatal=False

[api_database]
[barbican]
[cells]
[cinder]
os_region_name = RegionOne
[conductor]
[database]
connection = mysql://nova:mistack@c3-pt-compute23/nova
[ephemeral_storage_encryption]
[glance]
host = c3-pt-compute23
[guestfs]
[hyperv]
[image_file_url]
[ironic]
[keymgr]
[keystone_authtoken]
auth_uri = http://c3-pt-compute23:5000
auth_url = http://c3-pt-compute23:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
project_name = service
username = nova
password = mistack
[libvirt]
virt_type = kvm
[metrics]
[neutron]
url=http://c3-pt-compute23:9696
auth_url = http://c3-pt-compute23:35357
auth_plugin = password
project_domain_id = default
user_domain_id = default
region_name = RegionOne                                                                                                                                  
project_name = service
username = neutron
password = mistack

[osapi_v3]
[rdp]
[serial_console]
[spice]
[ssl]
[trusted_computing]
[upgrade_levels]
[vmware]
[workarounds]
[xenserver]
[zookeeper]
[matchmaker_redis]
[matchmaker_ring]
[oslo_concurrency]
lock_path = /var/run/nova
[oslo_messaging_amqp]
[oslo_messaging_qpid]
[oslo_messaging_rabbit]
rabbit_host = c3-pt-compute23
rabbit_userid = openstack
rabbit_password = mistack
[vnc]
vncserver_listen = 0.0.0.0
vncserver_proxyclient_address = 10.108.94.17
novncproxy_base_url = http://c3-pt-compute23:6080/vnc_auto.html

**Comment by guanyuding** [comment] 2016-03-17 11:30
@neiljerram 
I found a strange question.There are two different secgroups; and the result of neutron will be stored in etcd;

# neutron security-group-list 
+--------------------------------------+---------+------------------------------------------------------------+
| id                                   | name    | security_group_rules                                       |
+--------------------------------------+---------+------------------------------------------------------------+
| 149ab3f2-57a1-4a67-b18d-e484aad5157e | default | egress, IPv4, 1-65535/tcp, remote_ip_prefix: 0.0.0.0/0     |
|                                      |         | egress, IPv4, 1-65535/udp, remote_ip_prefix: 0.0.0.0/0     |
|                                      |         | egress, IPv4, icmp, remote_ip_prefix: 0.0.0.0/0            |
|                                      |         | ingress, IPv4, 1-65535/tcp, remote_ip_prefix: 0.0.0.0/0    |
|                                      |         | ingress, IPv4, 1-65535/udp, remote_ip_prefix: 0.0.0.0/0    |
|                                      |         | ingress, IPv4, icmp, remote_ip_prefix: 0.0.0.0/0           |
| a75b4093-8c7d-4998-ba01-ad460f853afc | www3    | egress, IPv4                                               |
|                                      |         | egress, IPv4, 1-65535/udp, remote_ip_prefix: 0.0.0.0/0     |
|                                      |         | egress, IPv6                                               |
|                                      |         | ingress, IPv4, 1-65535/udp, remote_ip_prefix: 0.0.0.0/0    |
| adfd9b7e-eb70-4d54-a110-4898c901a424 | ding    | egress, IPv4                                               |
|                                      |         | egress, IPv4, 67-68/udp, remote_ip_prefix: 10.108.94.0/24  |
|                                      |         | ingress, IPv4                                              |
|                                      |         | ingress, IPv4, 67-68/udp, remote_ip_prefix: 10.108.94.0/24 |
+--------------------------------------+---------+------------------------------------------------------------+
# nova secgroup-list
+----+---------+--------------------+
| Id | Name    | Description        |
+----+---------+--------------------+
| 1  | default | default            |
| 2  | terry   | allow ping and ssh |
+----+---------+--------------------+

There is no problem when  i use secgroup terry.   So Is not the installation of what I have less on my control node? 
Thanks~

**Comment by neiljerram** [comment] 2016-09-19 17:37
Hi @guanyuding.  I'm sorry to have forgotten this for so long.  Is the situation still the same as reported above?

**Comment by neiljerram** [comment] 2016-09-30 12:29
@guanyuding I'm going to close this as I guess it is no longer of immediate interest to you.  Please do feel free to reopen if it is of interest and still a problem.

**Closed by neiljerram** 2016-09-30 12:29 UTC
Labels: kind/support
