### ISSUE TITLE
Calico infos in etcd deleted automatically, causes bird_cfg_template config failed, key does not exist in path

### ISSUE THREAD

**Issue by bretagne-peiqi** [projectcalico/felix#2078] opened 2019-07-15 02:49 UTC
## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by rafaelvanoni** [comment] 2019-07-15 21:34
Could you please provide more context and fill out the issue template so we can get a better understanding of this problem?

**Comment by rafaelvanoni** [comment] 2019-07-15 21:35
Duplicate of #2079

**Closed by rafaelvanoni** 2019-07-15 21:35 UTC
Labels: kind/support
