### ISSUE TITLE
VM can't DHCP when re-using IP address

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#233] opened 2015-03-03 16:16 UTC
If I have a small DHCP pool and I repeatedly create/delete VMs until the pool wraps, my VM will fail to dhcp.  Syslog shows lots of messages like:

Mar  3 15:51:09 calico-L3-vm02 dnsmasq-dhcp[28804]: DHCPDISCOVER(ns-36493ed6-e3) fa:16:3e:88:30:14 no address available
Mar  3 15:51:24 calico-L3-vm02 dnsmasq-dhcp[28804]: not using configured address 10.65.0.13 because it is leased to fa:16:3e:c5:e6:27

**Comment by lwr20** [comment] 2015-03-03 16:19
Having discussed with @Lukasa, it seems that to hit this, the following all need to be true:
- you need to have wrapped the ip address pool within the dnsmasq dhcp lease period (this appears to be 1 day in my setup)
- you need to have terminated the VM which was using the IP address without releasing the lease (e.g. via Horizon)
- you need to be allocating the VM on the same host as previously had the VM with this IP address.

**Comment by Lukasa** [comment] 2015-03-03 17:04
I think this is really edge case: I don't consider this a high priority right now because I think it'll be really hard for people to actually hit this.

**Comment by fasaxc** [comment] 2015-05-20 18:38
The DHCP agent is supposed to handle this, I think.  It internally shells out to dhcp_release when a port is deleted.

**Comment by fasaxc** [comment] 2015-06-09 17:59
@matthewdupre I think one of the customers I'm supporting cares about this (they plan to use a small IP pool with high churn).  I think we need to bring it into 1.0.

**Comment by matthewdupre** [comment] 2015-06-11 17:14
OK, bringing it in.

**Comment by MatMeredith** [comment] 2015-06-12 10:10
FYI, I've repro'd this using the FV scripts this morning and this is still happening with the latest Calico code.  Trace from the compute hosts as follows...

Jun 12 09:53:15 calico-cidev14 dnsmasq[22870]: failed to create listening socket for fe80::261:feff:feed:cafe%tapf323d652-0a: Address already in use
Jun 12 09:53:16 calico-cidev14 dnsmasq-dhcp[21908]: DHCPDISCOVER(ns-67569dc2-c9) fa:16:3e:6d:bc:7b no address available
Jun 12 09:53:16 calico-cidev14 dnsmasq-dhcp[22870]: not using configured address 10.66.0.2 because it is leased to fa:16:3e:73:64:d4

**Comment by neiljerram** [comment] 2015-06-12 10:13
When this happens, does the dnsmasq config (at /var/lib/neutron/dhcp/<network-id>/host) still contain an entry for the old lease?

**Comment by neiljerram** [comment] 2015-06-12 11:28
@MatMeredith reran the test up to the point where one of the compute hosts had the following in syslog:

    Jun 12 12:01:48 calico-cidev12 ntpd[3907]: Listen normally on 18 tap28479a4d-69 fe80::261:feff:feed:cafe UDP 123
    Jun 12 12:01:48 calico-cidev12 ntpd[3907]: peers refreshed
    Jun 12 12:01:48 calico-cidev12 ntpd[3907]: new interface(s) found: waking up resolver
    Jun 12 12:02:46 calico-cidev12 dnsmasq-dhcp[23081]: not using configured address 10.66.0.2 because it is leased to fa:16:3e:b2:20:31
    Jun 12 12:02:46 calico-cidev12 dnsmasq-dhcp[22095]: DHCPDISCOVER(ns-94b9f16b-c7) fa:16:3e:38:9c:44 no address available
    Jun 12 12:02:46 calico-cidev12 dnsmasq-dhcp[23081]: DHCPDISCOVER(ns-05f369d9-63) fa:16:3e:38:9c:44 no address available
    Jun 12 12:03:46 calico-cidev12 dnsmasq-dhcp[23081]: not using configured address 10.66.0.2 because it is leased to fa:16:3e:b2:20:31
    Jun 12 12:03:46 calico-cidev12 dnsmasq-dhcp[23081]: DHCPDISCOVER(ns-05f369d9-63) fa:16:3e:38:9c:44 no address available

and at that point captured /var/lib/neutron/dhcp.  The relevant host file then had:

fa:16:3e:ff:ba:92,host-10-66-0-6.openstacklocal,10.66.0.6
fa:16:3e:38:9c:44,host-10-66-0-2.openstacklocal,10.66.0.2
fa:16:3e:86:d6:32,host-10-66-0-3.openstacklocal,10.66.0.3
fa:16:3e:59:29:ec,host-10-66-0-4.openstacklocal,10.66.0.4

which means that the old lease information for fa:16:3e:b2:20:31 had – correctly – been removed.

So, as @fasaxc’s comment implied, the issue is with the old VM not having released that lease, or with dnsmasq thinking that it hasn’t yet.

**Comment by Lukasa** [comment] 2015-06-23 13:11
I believe this is fundamentally an upstream issue: is that correct @neiljerram?

**Comment by fasaxc** [comment] 2015-06-24 21:46
@Lukasa @neiljerram Just to clarify.  In Juno, at least, this is what should happen:

* `dhcp_agent.py` calls reload_allocations on the dhcp driver
* that calls `self._release_unused_leases()`
* `_release_unused_leases()` calls `_release_lease()` for each IP that is no longer needed
* `_release_lease()` shells out to `dhcp_release`, which should be logged in the dhcp agent log.

Updating the hosts file isn't enough on its own.  I think dnsmasq keeps some internal state that prevents it from re-using the IP until it is released.

**Comment by fasaxc** [comment] 2015-06-29 14:02
@Lukasa It's upstream unless we've broken the DHCP release somehow.

**Comment by neiljerram** [comment] 2015-06-29 14:16
I had a partial look at this on Friday.  Suspect there is scope for us to have broken this - in that the aliasing connection between the ns-XXX interface and the TAP interfaces may not be understood by dhcp_release.

**Comment by neiljerram** [comment] 2015-06-29 14:17
In other words, possibly dhcp_release is being called, but it's not having the intended effect.

**Comment by neiljerram** [comment] 2015-06-29 14:19
Note that dhcp_release works by sending a DHCP_RELEASE protocol message - which the client should respond to, and then dnsmasq sees that response and removes the lease from its internal DB.  dhcp_release does _not_ directly modify dnsmasq's internal DB.

**Comment by fasaxc** [comment] 2015-06-29 14:30
Ah, then that may not help if the VM is torn down since it may not be able to respond.

**Comment by neiljerram** [comment] 2015-06-29 14:38
Indeed that's another possible problem.

**Comment by neiljerram** [comment] 2015-06-29 14:47
Sorry, just rechecked the man page, and it seems I got that all garbled.  There is a DHCP RELEASE protocol message, but it goes to the local server, i.e. dnsmasq.  Here's what the man page says:

       A  utility  which  forces  the  DHCP  server running on this machine to
       release a DHCP lease.

       Send a DHCPRELEASE message via the  specified  interface  to  tell  the
       local DHCP server to delete a particular lease.

       The interface argument is the interface in which a DHCP request _would_
       be received if it was coming from the client, rather than  being  faked
       up here.

       The address argument is a dotted-quad IP addresses and mandatory.

       The  MAC  address  is  colon separated hex, and is mandatory. It may be
       prefixed by an address-type byte followed by -, eg

       10-11:22:33:44:55:66

       but if the address-type byte is missing it is assumed to be 1, the type
       for ethernet. This encoding is the one used in dnsmasq lease files.

       The  client-id  is  optional.  If  it  is  "*" then it treated as being
       missing.

**Comment by neiljerram** [comment] 2015-06-29 15:08
Possible problems 1 and 2: DHCP agent does "dhcp_release ns-XXX [ip-addr] [mac-addr]", which delivers the DHCPRELEASE message on the ns-XXX interface.  But:

- ns-XXX is a dummy (as in 'ip link add type dummy') interface in Calico, and might not support delivering messages at all; so dnsmasq might not see anything

- a real DHCPRELEASE from a client would be received by dnsmasq on a tap123-ABCD interface; the difference between that and ns-XXX might be enough for dnsmasq to ignore the DHCPRELEASE.

And possible problem 3: even if the DHCP agent instead did "dhcp_release tap123-ABCD [ip-addr] [mac-addr]", and so avoided those first two problems, it could be that there is some processing in the RELEASE code path, to do with mapping the RX i/f to DHCP leases, that needs further extension for the aliasing that is configured by our use of the --bridge-interface option, compared to what we've done in the past for the DHCPDISCOVER code path.

**Comment by fasaxc** [comment] 2015-06-29 15:13
As per my comment on #15, maybe we really do need a bridge device or another solution for DHCP.  That would allow each dnsmasq to listen on its own dummy interface but the DHCP packets would get bridged to them all.

**Comment by fasaxc** [comment] 2015-06-29 16:04
@neiljerram "a real DHCPRELEASE from a client would be received by dnsmasq on a tap123-ABCD interface; the difference between that and ns-XXX might be enough for dnsmasq to ignore the DHCPRELEASE."  Looks like we specify the --bridge-interfaces option to tell dnsmasq to treat all taps as an alias for ns-xxx.

**Comment by fasaxc** [comment] 2015-06-29 16:06
Sorry, just saw your comment to that effect!

**Comment by neiljerram** [comment] 2015-06-30 00:08
I favour:

- debugging (e.g. attaching GDB to) dnsmasq to check whether it's seeing the DHCPRELEASE, and if so why it doesn't fully process it

- subject to consistency with any debugging findings, modify the DHCP agent to call dhcp_release with the correct TAP interface instead of the ns-XXX interface.

**Comment by eepyaich** [comment] 2015-08-03 11:33
@neiljerram @fasaxc What's the status here?  Should we be worrying about this in the 1.0 timeframe?

**Comment by ryadavgslab** [comment] 2015-10-12 12:19
Guys anyone has fix for this ?

**Comment by fasaxc** [comment] 2015-10-12 13:51
@ryadavgslab If possible, the easiest workaround is to make sure that your IP pool is big enough that you don't wrap it before the leases of removed VMs  time out.  Is that an option for you?  What sort of scale of deployment are you using and how big is your IP pool?

**Comment by ryadavgslab** [comment] 2015-10-12 14:20
Hi Shaun ,

Thank you for your quick reply.
I have a pool of /24 ip's. That is around 253 ips . but I don't think those
many are even being used. The moment I delete or terminate the vm from
dashboard the old IPs are released and the same ones are assigned to the
new one on the dashboard for new vms. When the vms are terminated they
don't really get released from dnsmasq cache and so that is when the new
ones with same IP but new Mac try to fetch the IP it says that the old is
already assigned to previous VMs NIC.

Thanks
Ravindra

**Comment by fasaxc** [comment] 2015-10-14 16:53
@ryadavgslab we don't see this unless we wrap the IP pool very quickly, are you saying that you see it immediately when creating a VM after deleting one?

What platform are you running on?  What OpenStack packages are you using?  Which version of Calico?

**Comment by eepyaich** [comment] 2015-10-20 10:53
Updating this to high priority, as it sounds like this is being seen in cases where the IP pool isn't being wrapped (so is more concerning than we originally thought).

**Comment by lwr20** [comment] 2015-11-10 10:19
Attempting to repro this on our systems - no luck so far.  In every scenario I've tried, I'm seeing that Openstack allocates the next IP in the pool.  I'm beginning to suspect there's some config somewhere which is required to repro this - and by implication that by changing config @ryadavgslab could work round this problem.

**Comment by neiljerram** [comment] 2015-11-10 10:57
In principle we could work backwards on this by reading the code and trying to infer what the relevant config is...  But I think that would be quite laborious and painful.

Also if the goal is just to repro, we should be able to do that by configuring a very small subnet.  Did you try that @lwr20 ?

**Comment by lwr20** [comment] 2015-11-11 15:32
@neiljerram Repro is not quite the goal here - I think we know how to repro it.  

My intent at the moment is to figure out what config options might be interesting here so that we can document a workaround - especially since the fix might be upstream (i.e. long fix time)

**Comment by lwr20** [comment] 2015-11-13 15:03
@ryadavgslab I'm not having much luck here.  Could you post your neutron.conf, nova.conf and dhcp-agent.conf files please?  Or alternatively just run the calico-diags script which will grab everything interesting :)

**Comment by neiljerram** [comment] 2016-01-27 10:48
I just mentioned this issue in a thread on the dnsmasq-discuss mailing list: http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2016q1/010273.html

**Comment by neiljerram** [comment] 2016-01-27 10:50
And Simon Kelley's reply: http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2016q1/010275.html:

"[It] looks like the problem there is exactly as you say: dnsmasq is
failing to allocate an address because it has run out of free
addresses because addresses have been consumed by machine which are
now "dead" but did not release their address when they died, so the
address is unavailable until the lease period expires."

**Comment by fasaxc** [comment] 2016-11-21 10:55
@lance there's a chance this issue may have been fixed by Neil's work to explicitly name the interfaces that dnsmasq should listen on (I think our hunch was that the bridge mode wasn't working).  In any case, I think this bug belongs against networking-calico.  Please can you move it to the launchpad bug tracker?

**Comment by fasaxc** [comment] 2017-01-19 17:38
Closing as stale.  It's either fixed or we can't repro!

**Comment by jinhao** [comment] 2018-01-09 12:37
anyone has fix for this ? facing similar issue on ocata Openstack, dnsmasq version 2.66

**Comment by jinhao** [comment] 2018-01-09 12:41
i capture the packet, get this as below:

    20:27:23.025886 IP 192.168.99.2 > 192.168.99.2: ICMP 192.168.99.2 udp port bootps unreachable, length 556
    20:27:23.026905 IP 192.168.99.2.40678 > 192.168.99.2.bootps: BOOTP/DHCP, Request, length 548

i saw dnsmasq is ok listening in port 67:

    udp        0      0 0.0.0.0:67              0.0.0.0:*                           20428/dnsmasq        off (0.00/0/0)

**Comment by fasaxc** [comment] 2018-01-09 13:31
@jinhao we weren't able to reproduce this last time we tried.  Please can you give us concrete steps to reproduce including:

- OS version
- OpenStack version
- OpenStack cluster details (number of nodes, any interesting configuration)
- Calico version
- OpenStack network configuration
- Steps to reproduce

**Comment by jinhao** [comment] 2018-01-10 00:40
@fasaxc  Thank you for your quick reply!

-  OS version CentOS Linux release 7.4.1708 Kernel 3.10.0-693.el7.x86_64
-  Openstack  ocata (3.8.1)
-  OpenStack cluster details: 3 network node, 12 compute node set dhcp_agents_per_network = 2 for HA;
-  we do't use Calico in Openstack
-  2 dhcp_agent , dhcp_lease_duration = 3600,  no specical configuration;
-  Steps:

     1. create 20 vm instance first time ,echo instance set 2 network(net01 & net02);
     2. delete the 20 vm all the same time；
     3. and then，we saw the host file for net01 & net02 dnsmasq is clean up correct,  the net01 lease file is clean up correct, but the net02 dnsmasq lease file only delete several ips；
     4. and if we see the netstat -su in the network namespace of the net02 dhcp，we can see: `UDP 
 xxx packets to unknown port received` , the xxx is same as the ip not clean up in net02 lease file；
     5. and if we capture the packet， the packet is below：

  ```
    20:27:23.025866 IP 192.168.99.2.54800 > 192.168.99.2.bootps: BOOTP/DHCP, Request, length 548
        20:27:23.025886 IP 192.168.99.2 > 192.168.99.2: ICMP 192.168.99.2 udp port bootps unreachable, length 556
        20:27:23.026905 IP 192.168.99.2.40678 > 192.168.99.2.bootps: BOOTP/DHCP, Request, length 548
        20:27:23.026925 IP 192.168.99.2 > 192.168.99.2: ICMP 192.168.99.2 udp port bootps unreachable, length 556
```

    Of course if we set vm only one nic， we  can also reproduce but two nic is easy to reproduce，
and we could also reproduce it buy execute dhcp_release command in the dhcp namespace manual, but not every time, in some dhcp namespace it's ok, some reproduce very easy.
juse like `ip netns exec qdhcp-0294bd05-58a2-4aaf-a3db-a0cc20f60171 sudo sh -c 'for i in {1..60}; do dhcp_release tap8b2f3086-50 192.168.44.6 fa:16:3e:77:93:c4; done'`

**Comment by fasaxc** [comment] 2018-01-10 09:33
@jinhao sorry, this is a Calico issue tracker, I can't help you diagnose a non-Calico DHCP agent.  Note: Calico has its own DHCP agent with several fixes in it, maybe you should try Calico!

**Closed by fasaxc** 2018-01-10 09:33 UTC
Labels: kind/bug, priority/P1

**Comment by jinhao** [comment] 2018-01-12 01:07
@fasaxc  OK, thanks， we already got it， it‘s a  bug of kernel.

**Comment by david-hill** [comment] 2018-04-03 02:58
@jinhao Do you have more information about that kernel bug ?
