### ISSUE TITLE
IPVS egress support fails to detect external IPs as forwarded

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1697] opened 2018-02-08 18:40 UTC
Seeing connectivity fail in my IPVS testing when a pod accesses a local-only external IP that loops back to itself.

Looks like we're not detecting that traffic as forwarded; the external IP looks like node port but the port used is the service port rather than the node port.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by song-jiang** [comment] 2018-10-04 17:41
@dawidmalina Yes. This issue is related to calico limitation on locally-assigned External IP.

Could you elaborate a bit on connectivity issues with your setup? AFAIU, Calico limitation will affect applying network policies on pods been exposed via locally-assigned External IP. If you see connectivity issue without network policy, it could be caused by something else. 

Just a thought, I noticed there was PR (https://github.com/kubernetes/kubernetes/pull/63066) merged upstream to fix IPVS external IP issue. Could you check if external IP been attached correctly to kube-ipvs0 interface?

**Comment by dawidmalina** [comment] 2018-10-05 17:38
I had issue with loadbalancing between all deployed pods behind service accessed by externalIP. The traffic was only passed to pods which were collocated on the same node as externalIP (keepalived pod deployed as daemonset). But to be honest i can't reproduce this issue any more on my local test environment. What is even more surprising - it's working properly :)

I need to validate this on real environment - maybe it was fixed somehow?

My environment details:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
2018-10-05 17:34:51.124 [INFO][59] daemon.go 138: Felix starting up GOMAXPROCS=4 buildDate="" gitCommit="6dbb7e0895177e1d26f4e3ccfc7ce30c59d2c246" version="v3.2.3"
```

**Comment by song-jiang** [comment] 2018-10-08 14:54
Yes. I am pretty certain the connectivity issue you had should have been fixed by the upstream PR.

**Comment by song-jiang** [comment] 2018-12-05 16:56
This issue is an kube-proxy issue and has been fixed by upstream PR https://github.com/kubernetes/kubernetes/pull/63066.

**Closed by song-jiang** 2018-12-05 16:56 UTC
Labels: priority/P2
