### ISSUE TITLE
calico-compute postinst script should be retired, or at least survive failures.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#983] opened 2016-02-24 21:58 UTC
It makes the calico-compute package uninstallable in a docker build (no iptables), and it's not as good as fixing the issues up at runtime anyway.

Ideally we'd get rid of the script, failing that allowing the postinst scripts to fail without aborting installation would make dockerisation possible.

https://git.openstack.org/cgit/openstack/networking-calico/tree/debian/calico-compute.postinst

If memory serves the DHCP checksum-fill rule isn't needed for Kilo and Liberty anyway, and we just needed to properly backport the fix to Icehouse / Juno.

The sysctls might be better set up on Felix startup (concern: will this work if Felix is running inside a container or that part of the filesystem emulated?).

**Comment by neiljerram** [comment] 2016-03-09 12:13
Bug for the networking-calico part of this: https://bugs.launchpad.net/networking-calico/+bug/1555056

@fasaxc Can you be precise about what of this you are targeting for the 1.4.0 milestone?  I guess you mean the sysctls, as that is the part of this that is achievable in Felix.

**Comment by fasaxc** [comment] 2016-03-09 13:38
@neiljerram I haven't thought in a lot of detail.  Just didn't want to drop that this was a pain point.

**Comment by fasaxc** [comment] 2016-09-08 09:52
Should we just live with this until liberty/mitaka are the norm?

**Comment by neiljerram** [comment] 2016-09-30 12:38
Closing this, as the issue is now more correctly tracked as a networking-calico bug at https://bugs.launchpad.net/networking-calico/+bug/1555056.

(My comment above talked about 'the networking-calico of this', implying that the sysctl aspect was not included in that.  But in fact it is, because right now those sysctl calls are made from a script that is part of networking-calico.  So the networking-calico bug covers everything here.)

**Closed by neiljerram** 2016-09-30 12:38 UTC
Labels: kind/enhancement, priority/P3, state/need-info
