### ISSUE TITLE
Asymmetrical routing with felix causes conntrack drops due to INVALID

### ISSUE THREAD

**Issue by bluecmd** [projectcalico/felix#1248] opened 2016-12-26 12:20 UTC
Hi,

I'm using GRE tunnels to move external traffic into my Kubernetes pods, but using direct server return to return the traffic. Due to this, there is no conntrack entry on the return traffic which causes felix to drop that traffic.

I would like to request a way to work around this. I'm open for things like whitelisting IP ranges or whatnot. One solution might be to only apply the felix forwarding rules on IPs that belong to the Pod CIDR / IPAM CIDR.

**Comment by fasaxc** [comment] 2016-12-26 16:22
Disabling that rule would mean trusting the pod not to spoof its IP, which is part of what Calico prevents, and it would negate the performance advantage of using conntrack. Could you assign a public IP to your pod and route traffic directly to it instead of tunneling traffic to it?

**Comment by bluecmd** [comment] 2016-12-26 19:54
Routing the IP directly the pod would be quite complicated but I guess doable. One of the reasons of using tunnels is to have a high level of control on the routing of the packets without requiring changes to propagate. The GRE ingress router would select the target pod and bind it to that client to provide session affinity (to not break TCP, but also to be useful) but could easily handle pod drains and failover - something that would be quite hard to achieve with normal routing alone.

Do you really need conntrack to avoid IP spoofing - wouldn't reverse-path route filtering be enough?

**Comment by fasaxc** [comment] 2017-01-03 10:03
Sorry, I was jumping ahead.  If you're doing DSR then I'm assuming that you're using a public-facing VIP that Calico doesn't know about, hence I was expecting the RPF check to fail (since Calico will only install routes to IPs that it's been told about).  If you have added your VIP to Calico's datastore then the RPF check would pass.  Otherwise, I'm not sure how those packets would be getting through to be dropped by the INVALID rule.

Beyond that, the fact that you're hitting the INVALID rule suggests that you're not hitting our ingress rules either (otherwise the packet would likely be conntracked on its way in).  Could you adjust your GRE setup so that the packets are decapsulated on the host so that they then get routed into the container's veth by Calico?

**Comment by bluecmd** [comment] 2017-01-03 10:43
Yes, I'm using DSR.

> Beyond that, the fact that you're hitting the INVALID rule suggests that you're not hitting our ingress rules either (otherwise the packet would likely be conntracked on its way in).
They are not, no.

> Could you adjust your GRE setup so that the packets are decapsulated on the host so that they then get routed into the container's veth by Calico?
The same issue applies here, it would result in sub-par load-balancing and draining would be a nightmare. Right now all routing intelligence is located in the GRE routers. They are free to select any pod that is reporting healthy, without any regard on what node it runs on. If I were to change it to be decapsulated on the host node it would require that node to:

- Have local routing logic and somehow know which local pod the traffic should be routed to. Imagine a case where you have 10 nodes and 11 pods - the non-crazy-complex solution would result in a traffic split of 1/10 on 9 of the pods and 1/20, 1/20 on the last two. And that's even without involving stateful things like draining or metric-based LB.
- Have node-global routing changes (kind of destroying a big part of the cleanliness of using a tunnel).

**Comment by fasaxc** [comment] 2017-01-03 11:09
> I have not told Calico anything about the VIPs. Traffic towards the VIPs are GRE encapsulated with a dst of the pod IP so why would Calico care?

My understanding of DSR is that the packet is sent to a VIP, say `12.0.0.1`, encapped and sent to the container, then the container responds with source address `12.0.0.1` directly.  In a Calico network, if Calico doesn't know about `12.0.0.1` then the response packet should be dropped because it's from a "spoofed" IP as far as calico is concerned.  That drop should happen in the kernel's RPF check because there should be no route to `12.0.0.1` via the pod's veth.

In any case, turning off the INVALID rule isn't the only problem here, I think what you're trying to do is more fundamentally at odds with how Calico currently works.  I've added an enhancement request to our internal tracking system.

**Comment by bluecmd** [comment] 2017-01-03 11:37
With regards to RPF, yes, that's 100% true and indeed the reason I'm not using RPF. My question was why you're using INVALID in addition to RPF, if the end goal is to prevent spoofing - RPF should be enough for the normal customer while allowing power-users control tree spoofing prevention through sysctl.

**Comment by fasaxc** [comment] 2017-01-03 11:46
The `INVALID` rule isn't to prevent spoofing, it is supposed to prevent traffic that is known to be invalid (due to incorrect sequence number or unknown connection) from passing any further.

Can you help me understand what it is that you're wanting to get out of using Calico?  Calico provides routing and security policy as its main features, but right now it seems like you want to bypass both our routing and security policy.

**Comment by bluecmd** [comment] 2017-01-03 11:51
Sure. Sorry if I'm being unclear.

I need Calico for providing routing for my pods, making their pod IPs reachable inside and outside the cluster.

I also need Calico to enforce security between my pods, through the network access policies.

I do not want Calico to interfere with any other traffic. I.e., pod to non-pod, non-pod to pod.

**Comment by tmjd** [comment] 2017-03-09 17:36
This conversation is getting a little stale and I can't say that I fully follow the conversation here but is there any conversation, answers, or feature requests that still need to come from this?

Would a feature request of "Allow a workload to spoof IP Addresses" be a concrete feature that would allow this outlined scenario to function?

**Comment by unicell** [comment] 2017-03-29 18:46
Sorry for inserting an off-topic question here.

@bluecmd I'm trying to do something very similar. But instead of turn off RPF completely, I used loose mode (rp_filter=2) inside namespace. However the same loose mode setting doesn't work outside of namespace. Probably due to some kernel bug related to veth and tunnel + RPF loose mode.[1]

Have you been bitten by the same issue, or you just turn off RPF outside of namespace (on node) as well?

[1] https://www.spinics.net/lists/netdev/msg390544.html

**Comment by xinuc** [comment] 2017-04-04 08:54
Hi @tmjd,
Yes, I think @bluecmd want calico to allow POD to spoof IP Addresses so we can use DSR.

Actually we also have the same problem, even after we disable RPF, we still can't spoof IP Addresses.

From what I read here
https://www.projectcalico.org/project-calico-needs-to-communicate-better/
in addition to RPF, calico also use iptables to prevent ip spoofing
```
Chain felix-from-a64e2126-8a (1 references)
pkts bytes target  prot opt in     out     source               destination
0     0 RETURN  all  —  any    any     10.0.0.10            anywhere             MAC FA:16:3E:2B:1E:5F
0     0 DROP    all  —  any    any     anywhere             anywhere             /* Default DROP if no match (endpoint a64e2126-8a88-4880-b482-4067b0593818): */
```

We also find that we can't just add iptables rules manually because they will be replaced by calico.

@tmjd @fasaxc is there any quick workaround so we can spoof IP address for now?

**Comment by fasaxc** [comment] 2017-04-04 09:07
@xinuc Looks like you're using a *very* old version of Calico.  Never versions do not police the source IP in iptables.  Please try with the latest stable release.  As I advised above, though, disabling the RPF check means that workloads can spoof their IPs, which negates Calico's security policy.

**Comment by fasaxc** [comment] 2017-04-07 10:28
Closing because I think the behaviour is working as designed.  @bluecmd if you want to discuss adding DSR as a feature, why don't you jump on our slack?

**Closed by fasaxc** 2017-04-07 10:28 UTC
Labels: area/felix, kind/support, priority/P3

**Comment by unicell** [comment] 2017-09-27 22:51
Recently started to deploy my DSR LB on Calico, and got bitten again by this issue. Had to follow the same approach @xinuc pointed me offline, to turn-off RPF by carrying custom patch on Felix.

On the other hand, found that conntrack INVALID iptable rule can be turned off by adding env override to calico/node daemonset spec.

>                 - name: FELIX_DISABLECONNTRACKINVALIDCHECK
>                   value: "true"

v2.4.1 is the Felix and the calico/node release I'm currently using.

**Comment by vishnukraj1111** [comment] 2019-05-13 04:54
Just to provide an update on this. The fix mentioned in most of the places echo 1 > /proc/sys/net/netfilter/ip_conntrack_tcp_be_liberal cause the conntrack table to be full and all connectivity to the servers were lost.
